pub const DIALOG_STATEMENT_FUNCTIONS: &[&str] = &["MsgBox", "InputBox", "DoEvents"];

pub const FILE_FUNCTIONS: &[&str] = &[
    "FreeFile",
    "EOF",
    "FileAttr",
    "LOF",
    "Loc",
    "Seek",
    "Dir",
    "GetAttr",
    "FileLen",
    "FileDateTime",
    "CurDir",
];

pub const DATE_TIME_FUNCTIONS: &[&str] = &[
    "Timer",
    "Now",
    "Date",
    "Time",
    "DateSerial",
    "TimeSerial",
    "DateValue",
    "TimeValue",
    "DateAdd",
    "DateDiff",
    "DatePart",
    "Year",
    "Month",
    "Day",
    "Hour",
    "Minute",
    "Second",
    "Weekday",
    "MonthName",
    "WeekdayName",
];

pub const FILE_SYSTEM_STATEMENT_FUNCTIONS: &[&str] = &["Kill", "MkDir", "RmDir", "ChDir"];

pub const BUILTIN_STATEMENT_FUNCTIONS: &[&str] =
    &["Randomize", "CallByName", "Kill", "MkDir", "RmDir", "ChDir"];

pub const STRING_ONE_ARG_FUNCTIONS: &[&str] = &[
    "Trim",
    "LTrim",
    "RTrim",
    "UCase",
    "LCase",
    "Chr",
    "ChrW",
    "Str",
    "Hex",
    "Oct",
    "Val",
    "StrReverse",
];

pub const STRING_FIXED_ARG_FUNCTIONS: &[&str] = &["Left", "Right", "Space", "String"];

pub const BOOLEAN_ONE_ARG_FUNCTIONS: &[&str] = &[
    "IsObject",
    "IsNull",
    "IsError",
    "IsEmpty",
    "IsNumeric",
    "IsDate",
];

pub const INTEGER_ONE_ARG_FUNCTIONS: &[&str] = &[
    "VarType", "Sgn", "Int", "Fix", "Len", "LenB", "Asc", "AscW", "LOF", "Loc", "Seek", "FileLen",
    "GetAttr", "Year", "Month", "Day", "Hour", "Minute", "Second",
];

pub const DOUBLE_ONE_ARG_FUNCTIONS: &[&str] =
    &["Abs", "Atn", "Cos", "Exp", "Log", "Sin", "Sqr", "Tan"];

pub const BUILTIN_FUNCTIONS: &[&str] = &[
    "Abs",
    "Atn",
    "Cos",
    "Exp",
    "Fix",
    "Log",
    "Sin",
    "Sqr",
    "Tan",
    "Round",
    "Sgn",
    "Int",
    "Randomize",
    "Rnd",
    "Split",
    "Join",
    "Filter",
    "CStr",
    "CVar",
    "CVErr",
    "StrComp",
    "IsObject",
    "IsArray",
    "IsNumeric",
    "IsDate",
    "IsNull",
    "IsEmpty",
    "IsError",
    "VarType",
    "TypeName",
    "CreateObject",
    "CByte",
    "CInt",
    "CLng",
    "CLngLng",
    "CLngPtr",
    "CInt64",
    "CSng",
    "CDbl",
    "CDec",
    "CCur",
    "CDate",
    "CBool",
    "Array",
    "LBound",
    "UBound",
    "Len",
    "LenB",
    "Left",
    "Right",
    "Mid",
    "Trim",
    "LTrim",
    "RTrim",
    "UCase",
    "LCase",
    "Replace",
    "InStr",
    "InStrRev",
    "Format",
    "FormatCurrency",
    "FormatDateTime",
    "FormatNumber",
    "FormatPercent",
    "Space",
    "String",
    "StrConv",
    "StrReverse",
    "Chr",
    "ChrW",
    "Asc",
    "AscW",
    "Val",
    "Str",
    "Hex",
    "Oct",
    "FreeFile",
    "EOF",
    "FileAttr",
    "LOF",
    "Loc",
    "Seek",
    "Dir",
    "GetAttr",
    "FileLen",
    "FileDateTime",
    "CurDir",
    "Environ",
    "Input",
    "Timer",
    "Now",
    "Date",
    "Time",
    "DateSerial",
    "TimeSerial",
    "DateValue",
    "TimeValue",
    "DateAdd",
    "DateDiff",
    "DatePart",
    "Year",
    "Month",
    "Day",
    "Hour",
    "Minute",
    "Second",
    "Weekday",
    "MonthName",
    "WeekdayName",
    "Choose",
    "Command",
    "DoEvents",
    "Kill",
    "MkDir",
    "RmDir",
    "ChDir",
    "DDB",
    "Error",
    "FV",
    "GetAllSettings",
    "GetObject",
    "GetSetting",
    "IIf",
    "IMEStatus",
    "InputBox",
    "IPmt",
    "IRR",
    "MacID",
    "MacScript",
    "MIRR",
    "MsgBox",
    "NPer",
    "NPV",
    "Partition",
    "Pmt",
    "PPmt",
    "PV",
    "QBColor",
    "Rate",
    "RGB",
    "Shell",
    "SLN",
    "Spc",
    "Switch",
    "SYD",
    "Tab",
    "IsMissing",
];

pub fn strip_vba_namespace(name: &str) -> &str {
    name.strip_prefix("VBA.").unwrap_or(name)
}

pub fn is_name_in(name: &str, names: &[&str]) -> bool {
    names
        .iter()
        .any(|candidate| name.eq_ignore_ascii_case(candidate))
}

pub fn is_builtin_function(name: &str) -> bool {
    is_name_in(strip_vba_namespace(name), BUILTIN_FUNCTIONS)
}
